---
- name: Add custom host entries
  ansible.builtin.blockinfile:
    path: /etc/hosts
    block: |
      {% for host in base_custom_hosts %}
      {{ host.ip }}   {{ host.aliases | join (' ') }}
      {% endfor %}
  when: base_custom_hosts | length

- name: Add custom IP adresses
  ansible.builtin.template:
    src: custom_ips.j2
    dest: /etc/network/interfaces.d/60-floating_ip
  notify: restart_network
  when: base_extra_ips | length
