prometheus_cadvisor_rules:
  - alert: ContainerHighCpuUtilization
    expr: (sum(rate(container_cpu_usage_seconds_total{name!=""}[3m])) BY (instance, name) * 100) > 80
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: '{% raw %}Container High CPU utilization (instance {{ $labels.instance }}){% endraw %}'
      description: '{% raw %}"Container CPU utilization is above 80%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}{% endraw %}'

  - alert: ContainerHighMemoryUsage
    expr: (sum(container_memory_working_set_bytes{name!=""}) BY (instance, name) / sum(container_spec_memory_limit_bytes > 0) BY (instance, name) * 100) > 80
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: '{% raw %}Container High Memory usage (instance {{ $labels.instance }}){% endraw %}'
      description: '{% raw %}"Container Memory usage is above 80%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}{% endraw %}'

  - alert: ContainerVolumeUsage
    expr: (1 - (sum(container_fs_inodes_free{name!=""}) BY (instance) / sum(container_fs_inodes_total) BY (instance))) * 100 > 80
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: '{% raw %}Container Volume usage (instance {{ $labels.instance }}){% endraw %}'
      description: '{% raw %}"Container Volume usage is above 80%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}{% endraw %}'

  - alert: ContainerHighThrottleRate
    expr: rate(container_cpu_cfs_throttled_seconds_total[3m]) > 1
    for: 2m
    labels:
      severity: warning
    annotations:
      summary: '{% raw %}Container high throttle rate (instance {{ $labels.instance }}){% endraw %}'
      description: '{% raw %}"Container is being throttled\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}{% endraw %}'
