---
- name: restart ntp
  ansible.builtin.systemd:
    name: "{{ ntp_daemon }}"
    state: restarted
  when: ntp_enabled | bool

- name: restart cron
  ansible.builtin.systemd:
    name: "{{ ntp_cron_daemon }}"
    state: restarted
  when: ntp_cron_handler_enabled | bool
