hcloud_user_data: |
  #cloud-config
  users:
    - name: ansible
      groups: users, sudo
      sudo: ALL=(ALL) NOPASSWD:ALL
      shell: /bin/sh
      ssh_authorized_keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCYJ8azeX453r/+rw/4ctv7LMVhFL++m4inMm0FAWYf5KyDcnRuadssNJmK4ryQ2YepwegQ+clIEgMTb/Ku9BDbx3SjJhYWgV+mJE0V/2m1wQbjNmClAfoYSz6AgPZUrzehBfNDCuHlOhT461iEUf8YM8gDgCsIogh4xbDZEe+Lj9RZrq8syuEfPj3VBlK/k7gKBe/6dGovYtltOH7g6fou8mcd4tOItpzbOw4IsZF0egWP+nbwGQE8/+jrLa8ipo6Q66QG2fs+oO6rM8ypXNXu28oS1r0ssEhk0wRePELWaIJWHvzXbIPkV7smXvnJvxWx/9lGN5DiwR2w6nepNDq35ryqBZXq6LL+Hle3w52+y43u/7pbhcGtp7BfKsIjtJzNgEJLjMUmiF54O5LGy/h4vpz+EtXX42tTBuXrkbmKTSJPUwcvCstCKzfqXnkDYxDbe2u0wokUSfVDt0zbO6jyJkl3LlQnfj+QGiY9LU6JlrWhKg3xCerCgQSKDpVnqggdaM2V3TeqK6W8zy496XZtiN2S7GorBWsYevDrpDAPEEtXvNbwo0Ltu7EhQVwMCnAxlRim1Ytxkzz3i5fKHsR1yQoPrFRicD8Zeiu6V5VGuFB7Klxam6LLsRRbnIgNWyOjeWiikEhO4i1cpVoOFxbAoc95fiEJw7tJXN46m4aLpQ== ansible_ffkbu
  package_update: true
  package_upgrade: true
  runcmd:
    - sed -i -e '/^\(#\|\)PermitRootLogin/s/^.*$/PermitRootLogin without-password/' /etc/ssh/sshd_config
    - sed -i -e '/^\(#\|\)PasswordAuthentication/s/^.*$/PasswordAuthentication no/' /etc/ssh/sshd_config
