---
- name: Create vaultwarden data volume
  ansible.builtin.file:
    path: "{{ vaultwarden_install_path }}"
    state: directory
    owner: "{{ vaultwarden_linux_user_name }}"
    group: "{{ vaultwarden_linux_group_name }}"
    mode: '0700'
