---
- name: Ensure systemd-networkd configuration files exist
  vars:
    # Profiles to iterate over. Using a single looped task is more performant
    # than multiple tasks.
    all_files:
      - type: link
        files: "{{ systemd_networkd_link | dict2items }}"
      - type: netdev
        files: "{{ systemd_networkd_netdev | dict2items }}"
      - type: network
        files: "{{ systemd_networkd_network | dict2items }}"
  ansible.builtin.template:
    src: systemd_networkd_config.j2
    dest: /etc/systemd/network/{{ item.1.key }}.{{ item.0.type }}
    owner: root
    group: systemd-network
    mode: "0640"
  loop: "{{ query('subelements', all_files, 'files') }}"
  loop_control:
    label: "type: {{ item.0.type }}, name: {{ item.1.key }}"
  notify: Restart systemd-networkd
  register: systemd_networkd_status

- name: Create custom routing tables
  ansible.builtin.template:
    src: rtable.conf.j2
    dest: /etc/iproute2/rt_tables.d/{{ item.name }}.conf
  loop: "{{ systemd_networkd_routing_tables }}"
  loop_control:
    label: "{{ item.name }}"
  when: systemd_networkd_routing_tables | length

- name: Set systemd_network_status task
  ansible.builtin.set_fact:
    systemd_networkd_status: "{{ systemd_networkd_status }}"

- name: Manage nsswitch configuration
  ansible.builtin.template:
    src: nsswitch.conf.j2
    dest: /etc/nsswitch.conf
    owner: root
    group: root
    mode: "0644"
  when: systemd_networkd_manage_nsswitch_config
  register: systemd_networkd_nssswitch_changed

- name: Set systemd_networkd_nssswitch_changed task
  ansible.builtin.set_fact:
    systemd_networkd_nssswitch_changed: "{{ systemd_networkd_nssswitch_changed }}"

# vim: set ts=2 sw=2:
