---
- name: Install dependencies
  ansible.builtin.package:
    name: "{{ grafana_dependencies }}"
    state: present
  register: _install_dep_packages
  until: _install_dep_packages is succeeded
  retries: 5
  delay: 2

- name: Remove conflicting grafana packages
  ansible.builtin.package:
    name: grafana-data
    state: absent
  register: _old_grafana_pkgs

- name: Clean apt cache
  ansible.builtin.command: apt clean
  when:
    - _old_grafana_pkgs is changed
    - ansible_pkg_mgr == "apt"
  tags: skip_ansible_lint

- block:
    - name: Add Nodesource apt key.
      ansible.builtin.include_role:
        name: apt-signing-key
      vars:
        url: "https://packages.grafana.com/gpg.key"
        key_name: grafana
        dearmor: true

    - name: Add Grafana repository [Debian/Ubuntu]
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/grafana-archive-keyring.gpg] https://packages.grafana.com/oss/deb stable main
        state: present
        update_cache: true
  when:
    - ansible_pkg_mgr == "apt"
  environment: "{{ grafana_environment }}"

- name: Install Grafana
  ansible.builtin.package:
    name: "{{ grafana_package }}"
    state: "{{ (grafana_version == 'latest') | ternary('latest', 'present') }}"
  retries: 5
  delay: 2
  notify: restart grafana
