---
# handlers file for unattended-upgrades
- name: restart_apt_upgrade_timer
  ansible.builtin.systemd:
    name: apt-daily-upgrade.timer
    state: restarted
    daemon_reload: true

- name: restart_apt_daily_timer
  ansible.builtin.systemd:
    name: apt-daily.timer
    state: restarted
    daemon_reload: true

- name: restart_post_upgrade_watcher
  ansible.builtin.systemd:
    name: post-upgrade.path
    state: restarted
    enabled: true
    daemon_reload: true