---
- name: Gather variables for each operating system
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution_file_variety | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_version.split('.')[0] }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - node_exporter_install
    - node_exporter_configure
    - node_exporter_run

- ansible.builtin.import_tasks: preflight.yml
  tags:
    - node_exporter_install
    - node_exporter_configure
    - node_exporter_run

- ansible.builtin.import_tasks: install.yml
  become: true
  when: (not __node_exporter_is_installed.stat.exists) or (__node_exporter_current_version_output.stdout_lines[0].split(" ")[2] != node_exporter_version)
  tags:
    - node_exporter_install

- ansible.builtin.import_tasks: textfile-collector-scripts_install.yml
  become: true
  tags:
    - node_exporter_install

- ansible.builtin.import_tasks: configure.yml
  become: true
  tags:
    - node_exporter_configure

- ansible.builtin.import_tasks: textfile-collector-scripts_configure.yml
  become: true
  tags:
    - node_exporter_configure

- name: Ensure Node Exporter is enabled on boot
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: node_exporter
    enabled: true
    state: started
  tags:
    - node_exporter_run
