freifunk_exporter_data_sources:
  - name: ffkbub-V2
    data_url: https://map.kbu.freifunk.net/data/ffkbub-V2/meshviewer.json
    port: 19252
  - name: ffkbuu-V2
    data_url: https://map.kbu.freifunk.net/data/ffkbuu-V2/meshviewer.json
    port: 19253
  - name: ffkbuk
    data_url: https://map.kbu.freifunk.net/data/ffkbuk/meshviewer.json
    port: 19254
  - name: ffkbuu
    data_url: https://map.kbu.freifunk.net/data/ffkbuu/meshviewer.json
    port: 19255
  - name: ffeu
    data_url: https://map.kbu.freifunk.net/data/ffeu/meshviewer.json
    port: 19256

freifunk_exporter_bind_address: 10.0.1.3
