---
# defaults file for homer
homer_watchtower_active: true
homer_container_name: homer

homer_ports:
  - 127.0.0.1:8999:8080

homer_dashboard_title: Serviceübersicht
homer_dashboard_subtitle: Freifunk KBU
homer_dashboard_footer: '<p>Freifunk KBU c/o Chaos Computer Club Cologne • <a href="https://kbu.freifunk.net">kbu.freifunk.net</a> • GitHub <a href="https://github.com/ff-kbu"><i class="fab fa-github-alt"></i></a></p>'
homer_dashboard_header: true
homer_dashboard_columns: 3
homer_dashboard_connectivity_check: true
homer_dashboard_default_layout: columns # 'columns' or 'list'
homer_dashboard_color_theme: dark # 'dark', 'light' or 'auto'


homer_colors:
  dark:
    highlight-primary: "#333333"
    highlight-secondary: "#dc0967"
    highlight-hover: "#333333"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.6)
    link: "#ffffff"
    link-hover: "#dc0967"
  light:
    highlight-primary: "#333333"
    highlight-secondary: "#dc0967"
    highlight-hover: "#333333"
    link: "#333333"
    link-hover: "#dc0967"

homer_services:
  - name: Collaboration
    icon: fa-sharp fa-solid fa-people-group
    items:
      - name: Etherpad
        keywords: etherpad collaboration docs
        url: https://pad.kbu.freifunk.net
        target: _blank
        logo: assets/logos/etherpad.webp
        subtitle: pad.kbu.freifunk.net
        type: Ping
        method: get
        endpoint: "https://{{ hostvars['vmffkbusv01'].ansible_host }}/status/9001"

      - name: Jitsi
        keywords: jitsi collaboration meeting
        url: https://meet.kbu.freifunk.net
        target: _blank
        logo: assets/logos/jitsi.png
        subtitle: meet.kbu.freifunk.net
        type: Ping
        method: get
        endpoint: "https://{{ hostvars['vmffkbusv01'].ansible_host }}/status/8000"

  - name: Administration
    icon: fa-sharp fa-solid fa-user-tie
    items:
      - name: UISP
        keywords: uisp ubiquiti management wifi
        url: https://uisp.kbu.freifunk.net
        target: _blank
        logo: assets/logos/uisp.png
        subtitle: uisp.kbu.freifunk.net
        type: Ping
        method: get
        endpoint: "https://{{ hostvars['vmffkbusv02'].ansible_host }}/status/9080"

      - name: Unifi
        keywords: unifi ubiquiti management wifi
        url: https://unifi.kbu.freifunk.net
        target: _blank
        logo: assets/logos/unifi.png
        subtitle: unifi.kbu.freifunk.net
        type: Ping
        method: get
        endpoint: "https://{{ hostvars['vmffkbusv02'].ansible_host }}/status/8443"

      - name: DynV6
        keywords: dyndns dns
        url: https://dynv6.com/
        target: _blank
        logo: assets/logos/dynv6.png
        subtitle: dynv6.com

  - name: Docker
    icon: fa-brands fa-docker
    items:
      - name: "Portainer {{ hostvars['vmffkbusv01'].inventory_hostname }}"
        keywords: docker portainer
        url: "https://{{ hostvars['vmffkbusv01'].ansible_host }}/portainer"
        target: _blank
        logo: assets/logos/portainer.webp
        subtitle: "{{ hostvars['vmffkbusv01'].ansible_host }}/portainer"
        type: Ping
        method: get
        endpoint: "https://{{ hostvars['vmffkbusv01'].ansible_host }}/status/9000"

      - name: "Portainer {{ hostvars['vmffkbusv02'].inventory_hostname }}"
        keywords: docker portainer
        url: "https://{{ hostvars['vmffkbusv02'].ansible_host }}/portainer"
        target: _blank
        logo: assets/logos/portainer.webp
        subtitle: "{{ hostvars['vmffkbusv02'].ansible_host }}/portainer"
        type: Ping
        method: get
        endpoint: "https://{{ hostvars['vmffkbusv01'].ansible_host }}/status/9000"

  - name: Metrik
    icon: fa-solid fa-sharp fa-magnifying-glass-chart
    items:
      - name: Grafana
        keywords: grafana monitoring
        url: https://grafana.kbu.freifunk.net
        target: _blank
        logo: assets/logos/grafana.png
        subtitle: grafana.kbu.freifunk.net
        type: Ping
        method: get
        endpoint: "https://{{ hostvars['vmffkbusv01'].ansible_host }}/status/3000"

      - name: Prometheus
        keywords: prometheus monitoring
        url: https://grafana.kbu.freifunk.net/prometheus
        target: _blank
        logo: assets/logos/prometheus.png
        subtitle: grafana.kbu.freifunk.net/prometheus
        type: Ping
        method: get
        endpoint: "https://{{ hostvars['vmffkbusv01'].ansible_host }}/status/9090"

      - name: Alertmanager
        keywords: alertmanager monitoring
        url: https://grafana.kbu.freifunk.net/alertmanager
        target: _blank
        logo: assets/logos/alertmanager.svg
        subtitle: grafana.kbu.freifunk.net/alertmanager
        type: Ping
        method: get
        endpoint: "https://{{ hostvars['vmffkbusv01'].ansible_host }}/status/9093"

homer_message:
  url: https://api.rss2json.com/v1/api.json?rss_url=https%3A%2F%2Fstatus.hetzner.com%2Fde.atom
  mapping:
    content: status
  title: Hetzner Cloud Status
  icon: fa-sharp fa-solid fa-gears
