---
- name: Preflight | Populate service facts
  ansible.builtin.service_facts:

- name: Preflight | Assert that docker is installed
  ansible.builtin.assert:
    that: "'docker' in services"
    msg: "This role requires docker"

- name: Preflight | Assert that certbot is installed
  ansible.builtin.assert:
    that: "'certbot.service' in services"
    msg: "This role requires certbot"
  when: unifi_ssl_letsencrypt_enabled | bool
