---
# defaults file for homer
homer_image_tag: latest
homer_install_path: /opt/homer
homer_restart_policy: always
homer_watchtower_active: false
homer_container_name: homer

homer_ports:
  - 8080:8080

homer_dashboard_title: App dashboard
homer_dashboard_subtitle: Homer
homer_dashboard_footer: '<p>Created with <span class="has-text-danger">❤️</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>'
homer_dashboard_header: true
homer_dashboard_columns: 3
homer_dashboard_connectivity_check: true
homer_dashboard_default_layout: columns # 'columns' or 'list'
homer_dashboard_color_theme: auto # 'dark', 'light' or 'auto'


homer_colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#424242"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
    background-image: "assets/your/light/bg.png"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"
    background-image: "assets/your/dark/bg.png"

homer_links: []

homer_services: []

homer_message: ""
