---
- name: Preflight | Populate service facts
  ansible.builtin.service_facts:

- name: Preflight | Assert that docker is installed
  ansible.builtin.assert:
    that: "'docker' in services"
    msg: "This role requires docker"
