---
- name: Create csr dir
  ansible.builtin.file:
    path: /etc/ssl/csr
    state: directory

- name: Generate an OpenSSL private key.
  community.crypto.openssl_privatekey:
    path: "/etc/ssl/private/{{ ansible_hostname }}.pem"

- name: Generate an OpenSSL CSR.
  community.crypto.openssl_csr:
    path: "/etc/ssl/csr/{{ ansible_hostname }}.csr"
    privatekey_path: "/etc/ssl/private/{{ ansible_hostname }}.pem"
    common_name: "{{ ansible_hostname }}"

- name: Generate a self signed OpenSSL certificate
  community.crypto.x509_certificate:
    path: "/etc/ssl/certs/{{ ansible_hostname }}.crt"
    privatekey_path: "/etc/ssl/private/{{ ansible_hostname }}.pem"
    csr_path: "/etc/ssl/csr/{{ ansible_hostname }}.csr"
    provider: selfsigned
