---
# tasks file for bird
- name: Install bird
  ansible.builtin.apt:
    name: bird2

- name: Create bird conf.d directory
  ansible.builtin.file:
    path: /etc/bird/conf.d
    state: directory
    owner: "{{ bird_user }}"
    group: "{{ bird_group }}"
    mode: "0755"

- name: Write bird configuration
  ansible.builtin.template:
    src: bird.conf.j2
    dest: "/etc/bird/bird.conf"
    owner: "{{ bird_user }}"
    group: "{{ bird_group }}"
    mode: "0644"
  notify:
    - check_bird_configuration
    - reload_bird

- name: Write bird protocol configuration
  ansible.builtin.template:
    src: "protocols/{{ item }}.conf.j2"
    dest: "/etc/bird/conf.d/{{ item }}.conf"
    owner: "{{ bird_user }}"
    group: "{{ bird_group }}"
    mode: "0644"
  loop: "{{ bird_protocols | map(attribute='protocol') | list | unique }}"
  notify:
    - check_bird_configuration
    - reload_bird

- name: Create logfile
  ansible.builtin.file:
    path: "{{ bird_log_file }}"
    state: touch
    owner: "{{ bird_user }}"
    group: "{{ bird_group }}"
    mode: "0644"
  notify:
    - check_bird_configuration
    - reload_bird

- name: Set sysctl configuration
  ansible.builtin.template:
    src: sysctl.conf.j2
    dest: /etc/sysctl.d/99-sysctl.conf
  notify: apply_sysctl

- name: Create bird systemd configuration directory
  ansible.builtin.file:
    path: /etc/systemd/system/bird.service.d/
    state: directory
    owner: root
    group: root
    mode: "0755"
  when: bird_systemd_aware
