---
- name: Setup | add distribution-specific variables
  ansible.builtin.include_vars: "{{ ansible_distribution }}.yml"

- name: Setup | add Debian Wheezy workaround
  ansible.builtin.include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
  when: (ansible_distribution == "Debian") and (ansible_distribution_release == "wheezy")

- name: Setup | add Debian Bullseye workaround
  ansible.builtin.include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml"
  when: (ansible_distribution == "Debian") and (ansible_distribution_release == "bullseye")

- name: Setup | install powermgmt-base
  ansible.builtin.apt:
    pkg:
    state: present
    cache_valid_time: "{{ unattended_cache_valid_time }}"
    update_cache: true
  when: unattended_only_on_ac_power

- name: Setup | install unattended-upgrades
  ansible.builtin.apt:
    pkg: unattended-upgrades
    state: present
    cache_valid_time: "{{ unattended_cache_valid_time }}"
    update_cache: true

- name: Setup | install reboot dependencies
  ansible.builtin.include_tasks: reboot.yml
  when: unattended_automatic_reboot|bool

- name: Configuration | create APT auto-upgrades configuration
  ansible.builtin.template:
    src: auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: "0644"

- name: Configuration | create unattended-upgrades configuration
  ansible.builtin.template:
    src: unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    owner: root
    group: root
    mode: "0644"

- name: Configuration | Create '/etc/systemd/system/apt-daily-upgrade.timer.d'
  ansible.builtin.file:
    path: /etc/systemd/system/apt-daily-upgrade.timer.d
    state: directory

- name: Configuration | Create '/etc/systemd/system/apt-daily.timer.d'
  ansible.builtin.file:
    path: /etc/systemd/system/apt-daily.timer.d
    state: directory

- name: Configuration | Add upgrade cron override
  ansible.builtin.template:
    src: override_upgrade.conf.j2
    dest: /etc/systemd/system/apt-daily-upgrade.timer.d/override.conf
  notify: restart_apt_upgrade_timer

- name: Configuration | Add update cron override
  ansible.builtin.template:
    src: override_update.conf.j2
    dest: /etc/systemd/system/apt-daily.timer.d/override.conf
  notify: restart_apt_daily_timer

- name: Configuration | Add post-upgrade command watcher
  ansible.builtin.template:
    src: "{{ item }}"
    dest: "/etc/systemd/system/{{ item | basename | regex_replace('\\.j2$') }}"
  notify: restart_post_upgrade_watcher
  with_fileglob: templates/post-upgrade.*.j2
  when: unattended_post_commands | length