---
# tasks file for pstat
- name: Create directory
  ansible.builtin.file:
    path: "{{ pstat_directory }}"
    mode: "0750"
    state: directory

- name: Copy script
  ansible.builtin.template:
    src: pstat.py.j2
    dest: "{{ pstat_directory }}/pstat.py"
    mode: "0640"
  notify: restart_pstat

- name: Copy systemd service
  ansible.builtin.template:
    src: pstat.service.j2
    dest: /etc/systemd/system/pstat.service
    mode: "0640"
  notify: restart_pstat
