name: Lint

on:
  pull_request:
    paths:
      - '**/*.sh'
      - '**/*.yml'
      - '**/*.yaml'
      - '**/*.j2'

jobs:
  changes:
    runs-on: ubuntu-22.04
    outputs:
      ansible: ${{ steps.filter.outputs.ansible }}
      shell: ${{ steps.filter.outputs.shell }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # fetch full history so origin/<branch> exists

      - name: Filter changed files
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            ansible:
              - '**/*.yml'
              - '**/*.yaml'
              - '**/*.j2'
            shell:
              - '**/*.sh'

  verify_ansible:
    needs: changes
    if: needs.changes.outputs.ansible == 'true'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4

      - name: Install Ansible and Ansible Lint
        run: |
          BASE_BRANCH=${{ github.base_ref }}
          echo "Comparing against origin/$BASE_BRANCH"
          git fetch origin $BASE_BRANCH

          docker run --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /workspace \
          ghcr.io/ansible/community-ansible-dev-tools:latest \
          bash -c "
            git config --global --add safe.directory /workspace &&
            ansible --version &&
            ansible-lint --version &&
            cat verify_lint.sh | bash || true &&
            cat verify_pb.sh | bash || true &&
            cat verify_j2.sh | bash || true
          "

  shellcheck:
    needs: changes
    if: needs.changes.outputs.shell == 'true'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install ShellCheck
        run: sudo apt-get install -y shellcheck

      - name: Run ShellCheck
        run: ./runShellcheck.sh
