name: Lint

on:
  pull_request:
    paths:
      - '**/*.sh'
      - '**/*.yml'
      - '**/*.yaml'
      - '**/*.j2'

jobs:
  changes:
    runs-on: ubuntu-22.04
    outputs:
      ansible: ${{ steps.filter.outputs.ansible }}
      shell: ${{ steps.filter.outputs.shell }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   # fetch full history so origin/<branch> exists

      - name: Filter changed files
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            ansible:
              - '**/*.yml'
              - '**/*.yaml'
              - '**/*.j2'
            shell:
              - '**/*.sh'

  verify_ansible:
    needs: changes
    if: needs.changes.outputs.ansible == 'true'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4

      - name: Install Ansible and Ansible Lint
        run: |
          python -m pip install --upgrade pip pipx
          pipx install ansible
          pipx install ansible-lint
          ansible --version
          ansible-lint --version

      - name: Run verify scripts
        run: |
          BASE_BRANCH=${{ github.base_ref }}
          echo "Comparing against origin/$BASE_BRANCH"
          git fetch origin $BASE_BRANCH
          cat verify_lint.sh | /bin/sh || true
          cat verify_pb.sh | /bin/sh || true
          cat verify_j2.sh | /bin/sh || true

  shellcheck:
    needs: changes
    if: needs.changes.outputs.shell == 'true'
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install ShellCheck
        run: sudo apt-get install -y shellcheck

      - name: Run ShellCheck
        run: ./runShellcheck.sh
