{
 "title": "Bind9 DNS",
 "description": "Bind9 DNS Service Statistics.",
 "tags": [
  "bind",
  "dns",
  "bind-exporter",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "job", "label": "Job", "query": { "query": "label_values(bind_up, job)" } },
   {
    "name": "node",
    "label": "Host:",
    "query": {
     "query": "label_values(bind_up, instance)"
    }
   },
   {
    "name": "port",
    "label": "Port",
    "query": {
     "query": "label_values(bind_up{instance=~\"$node:(.*)\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Restarted",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "${__to:date:seconds} - max(bind_boot_time_seconds{instance=~\"$node:.*\"}) "
    }
   ]
  },
  {
   "title": "Reconfigured",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "${__to:date:seconds} - max(bind_config_time_seconds{instance=~\"$node:.*\"})"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bind_query_duplicates_total{instance=\"$node:$port\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Duplicates"
    },
    {
     "expr": "increase(bind_query_errors_total{instance=\"$node:$port\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ error }}"
    },
    {
     "expr": "increase(bind_query_recursions_total{instance=\"$node:$port\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "Recursions"
    }
   ]
  },
  { "title": "Incoming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Incoming Queries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bind_incoming_queries_total{instance=\"$node:$port\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Incoming Request Opcodes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bind_incoming_requests_total{instance=\"$node:$port\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ opcode }}"
    }
   ]
  },
  {
   "title": "Response Results",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bind_responses_total{instance=\"$node:$port\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ result }}"
    }
   ]
  },
  { "title": "Resolver", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Resolver Response Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bind_resolver_response_errors_total{instance=\"$node:$port\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ view }} / {{ error }}"
    },
    {
     "expr": "increase(bind_resolver_response_lame_total{instance=\"$node:$port\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ view }} / LAME"
    },
    {
     "expr": "increase(bind_resolver_response_mismatch_total{instance=\"$node:$port\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ view }} / MISMATCH"
    },
    {
     "expr": "increase(bind_resolver_response_truncated_total{instance=\"$node:$port\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ view }} / TRUNCATED"
    }
   ]
  },
  {
   "title": "Resolver Queries",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bind_resolver_queries_total{instance=\"$node:$port\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ view }} / {{ type }}"
    }
   ]
  },
  {
   "title": "Query Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bind_resolver_query_errors_total{instance=\"$node:$port\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ view }} / {{ error }}"
    },
    {
     "expr": "increase(bind_resolver_query_edns0_errors_total{instance=\"$node:$port\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ view }} / EDNS0"
    },
    {
     "expr": "increase(bind_resolver_query_retries_total{instance=\"$node:$port\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ view }} / Retry"
    }
   ]
  },
  {
   "title": "Query By Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bind_resolver_query_duration_seconds_bucket{instance=\"$node:$port\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ view }} / {{ le }}"
    }
   ]
  },
  {
   "title": "Resolver Cache RR Sets",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "bind_resolver_cache_rrsets{instance=\"$node:$port\",job=\"$job\"}",
     "legendFormat": "{{ view }} / {{ type }}"
    }
   ]
  },
  {
   "title": "DNSSEC Validation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(bind_resolver_dnssec_validation_errors_total{instance=\"$node:$port\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ view }} / ValErr"
    },
    {
     "expr": "increase(bind_resolver_dnssec_validation_success_total{instance=\"$node:$port\",job=\"$job\"}[$__rate_interval])",
     "legendFormat": "{{ view }} / {{ result }}"
    }
   ]
  }
 ]
}