{
 "title": "Bird",
 "description": "Metrics of BIRD routing daemon to use with Prometheus for use with https://github.com/czerwonk/bird_exporter",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "env",
    "query": {
     "query": "label_values(node_uname_info,env)"
    }
   },
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values(bird_protocol_up{env=\"$env\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "BGP Sessions Up",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "count(bird_protocol_up{instance=~\"$host\",proto=\"BGP\",state=\"Established\",state!=\"\"})",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "legendFormat": "{{name}}",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "BGP Sessions Down",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "count(bird_protocol_up{instance=~\"$host\",proto=\"BGP\",state!=\"Established\",state!=\"\"})",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "legendFormat": "{{name}}",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "BGP Sessions Down",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "bird_protocol_up{instance=~\"$host\",proto=\"BGP\",state!=\"Established\",state!=\"\"}",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "legendFormat": "{{name}}",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  { "title": "$host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }, "repeat": "host" },
  {
   "title": "BGP Updates Accepted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "sum by (ip_version) (bird_protocol_changes_update_import_accept_count{instance=~\"$host\",proto=\"BGP\",export_filter=\"ACCEPT\"})",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "legendFormat": "In {{name}} IPv{{ ip_version }}",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "round": "0s"
    },
    {
     "dateTimeType": "DATETIME",
     "expr": "sum by (ip_version) (bird_protocol_changes_update_export_accept_count{instance=~\"$host\",proto=\"BGP\",export_filter=\"ACCEPT\"})",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "legendFormat": "Out {{name}} IPv{{ ip_version }}",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "BGP Updates Rejected",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "sum by (ip_version) (bird_protocol_changes_update_import_reject_count{instance=~\"$host\",proto=\"BGP\"})",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "legendFormat": "In {{name}} IPv{{ ip_version }}",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "round": "0s"
    },
    {
     "dateTimeType": "DATETIME",
     "expr": "sum by (ip_version) (bird_protocol_changes_update_export_reject_count{instance=~\"$host\",proto=\"BGP\"})",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "legendFormat": "Out {{name}} IPv{{ ip_version }}",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "BGP Updates Ignored",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "sum by (ip_version) (bird_protocol_changes_update_import_ignore_count{instance=~\"$host\",proto=\"BGP\"})",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "legendFormat": "In {{name}} IPv{{ ip_version }}",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "round": "0s"
    },
    {
     "dateTimeType": "DATETIME",
     "expr": "sum by (ip_version) (bird_protocol_changes_update_export_ignore_count{instance=~\"$host\",proto=\"BGP\"})",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "legendFormat": "Out {{name}} IPv{{ ip_version }}",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "BGP Prefered",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "sum by (name) (bird_protocol_prefix_preferred_count{instance=~\"$host\",proto=\"BGP\",ip_version=\"4\"})",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "legendFormat": "{{name}} IPv4",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "round": "0s"
    },
    {
     "dateTimeType": "DATETIME",
     "expr": "sum by (name) (bird_protocol_prefix_preferred_count{instance=~\"$host\",proto=\"BGP\",ip_version=\"6\"})",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "legendFormat": "{{name}} IPv6",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "OSPF Updates Accepted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "expr": "sum by (ip_version) (bird_protocol_changes_update_import_accept_count{instance=~\"$host\",proto=~\"(OSPF|OSPFv3)\",export_filter=\"ACCEPT\"})",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "legendFormat": "In {{name}} IPv{{ ip_version }}",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "round": "0s"
    },
    {
     "dateTimeType": "DATETIME",
     "expr": "sum by (ip_version) (bird_protocol_changes_update_export_accept_count{instance=~\"$host\",proto=~\"(OSPF|OSPFv3)\",export_filter=\"ACCEPT\"})",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "legendFormat": "Out {{name}} IPv{{ ip_version }}",
     "query": "SELECT\n    $timeSeries as t,\n    count()\nFROM $table\nWHERE $timeFilter\nGROUP BY t\nORDER BY t",
     "round": "0s"
    }
   ]
  }
 ]
}