{
 "title": "FFKBU",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "ff_hood",
    "label": "Hood",
    "query": {
     "query": "label_values(freifunk__collector_up,hood)"
    }
   },
   {
    "name": "ff_node_name",
    "label": "Node",
    "query": {
     "query": "label_values(freifunk_router_meta{hood=\"$ff_hood\"}, name)"
    }
   },
   {
    "name": "ff_node_id",
    "query": {
     "query": "label_values(freifunk_router_meta{name=~\"$ff_node_name\"}, id)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Hood Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(freifunk__collector_up{hood=~\"$ff_hood\"}[15m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Total Clients",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (hood) (last_over_time(freifunk_router_client_count_total{hood=\"$ff_hood\"}[15m]))"
    }
   ]
  },
  {
   "title": "Current Total nodes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (hood) (last_over_time(freifunk_router_meta{hood=~\"$ff_hood\"}[15m]))"
    }
   ]
  },
  {
   "title": "Last Update",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "last_over_time(freifunk_info_timestamp{hood=~\"$ff_hood\"}[15m]) * 1000",
     "legendFormat": "{{ hood }}"
    }
   ]
  },
  {
   "title": "Client History",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (connection) (last_over_time(freifunk_router_client_count_total{hood=\"$ff_hood\"}[$__range]))",
     "legendFormat": "Clients {{ connection }}"
    }
   ]
  },
  {
   "title": "Top Nodes",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "topk(3,max by (id) (freifunk_router_client_count_total{hood=\"$ff_hood\"})) * on(id) group_left(name) (freifunk_router_meta{hood=\"$ff_hood\"})"
    }
   ]
  },
  {
   "title": "Firmware Distribution",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "count by (firmware) (count_over_time (freifunk_router_meta{hood=\"$ff_hood\"}[15m]))"
    }
   ]
  },
  { "title": "Node Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Name",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by (name) (last_over_time(freifunk_router_meta{id=~\"$ff_node_id\"}[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hardware",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by (hardware) (last_over_time(freifunk_router_meta{id=\"$ff_node_id\"}[15m]))",
     "legendFormat": "{{ hardware }}"
    }
   ]
  },
  {
   "title": "Firmware",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group by (firmware) (last_over_time(freifunk_router_meta{id=\"$ff_node_id\"}[15m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Client History",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (id,connection) (freifunk_router_client_count_total{hood=\"$ff_hood\"}) * on(id) group_left(name) (freifunk_router_meta{hood=\"$ff_hood\",name=\"$ff_node_name\"})",
     "legendFormat": "Clients {{ connection }}"
    }
   ]
  },
  {
   "title": "Node System Load",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(freifunk_router_load_avg_5m{id=\"$ff_node_id\"}[$__range])",
     "legendFormat": "System Load"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg_over_time(freifunk_router_memory_usage_total{id=~\"$ff_node_id\"}[$__range])",
     "legendFormat": "Memory Usage"
    }
   ]
  }
 ]
}