{
 "title": "nginx",
 "description": "Official dashboard for nginx prometheus exporter",
 "tags": [
  "nginx",
  "prometheus",
  "nginx prometheus exporter"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(nginx_up {env=\"$env\"}, instance)"
   },
   {
    "name": "env",
    "label": "env",
    "query": "label_values(nginxexporter_build_info, env)"
   }
  ]
 },
 "panels": [
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Processed connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Connections (rate)" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_connections_accepted{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} accepted"
    },
    {
     "expr": "irate(nginx_connections_handled{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} handled"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "nginx_connections_active{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} active"
    },
    {
     "expr": "nginx_connections_reading{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} reading"
    },
    {
     "expr": "nginx_connections_waiting{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} waiting"
    },
    {
     "expr": "nginx_connections_writing{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} writing"
    }
   ]
  },
  {
   "title": "Requests rate per 5m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(nginx_http_requests_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}} total requests"
    }
   ]
  }
 ]
}